services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Kafka escucha en todas las interfaces
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      # Kafka anuncia la IP real de tu máquina
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9092
      # Necesario en entornos de prueba (1 broker)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1